services:
  - type: web
    name: terabox-player
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    buildpacks:      # <-- YEH BADLAV HAI (P chota kar diya hai)
      - url: https://github.com/jontewks/puppeteer-heroku-buildpack
    envVars:
      - key: NODE_ENV
        value: production
